spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/entrygraph
spring.datasource.username=vidhijain
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true

# Actuator
management.endpoints.web.exposure.include=health
